default:
  image: ruby:2.6.6

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: basic_health_units_test
  POSTGRES_USER: user
  POSTGRES_PASSWORD: BhU2020!
  POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - gem install dpl

stages:
  - Test
  - Production

Enviromnent_Test:
  stage: Test
  environment: test
  only:
    - tags
    - branches
  when: manual
  allow_failure: false
  script:
    - bundle install
    - bundle exec rails db:migrate RAILS_ENV=test
    - bundle exec rspec
Enviromnent_Production:
  stage: Production
  environment: production
  when: manual
  only:
    - tags
  allow_failure: true
  script:
    - bundle install
    - bundle exec rails db:migrate RAILS_ENV=production
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_API_KEY
